SET FEEDBACK 1
SET NUMWIDTH 10
SET LINESIZE 80
SET TRIMSPOOL ON
SET TAB OFF
SET PAGESIZE 100
SET ECHO OFF

CONNECT scloud/&scloud_pass

DROP TABLE users CASCADE CONSTRAINTS;
DROP TABLE files CASCADE CONSTRAINTS;

COMMIT;